try {  
  throw new Error('Something bad happened');
}
catch(e) {  
  console.log(e);
}